#!/usr/bin/env python3
"""Regenerate RecitationKit's token table and I/O manifest from the spec vectors.

  python3 tools/generate-swift-tables.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "RecitationKit/Sources/RecitationKit"
toks = json.loads((ROOT / "spec/vectors/tokens.json").read_text())
io = json.loads((ROOT / "spec/vectors/zipformer_io.json").read_text())
assert toks["blankId"] == 250 and len(toks["tokens"]) == 251


def esc(s):
    return "".join("\\" + c if c in '\\"' else c for c in s)


lines = ["// Generated by tools/generate-swift-tables.py from spec/vectors/tokens.json. Do not edit.", "",
         "/// The 251 CTC output symbols of the Zipformer (spec §3). Index = class id; 250 is blank.",
         "public let zipformerTokens: [String] = ["]
lines += [f'  "{esc(t)}",' for t in toks["tokens"]] + ["]"]
(SRC / "Tokens.generated.swift").write_text("\n".join(lines) + "\n")

lines = ["// Generated by tools/generate-swift-tables.py from the shipped model manifest. Do not edit.", "",
         "extension ZipformerIO {",
         "  /// I/O manifest of `zipformer_interp_gentle_a05.int8.onnx`: window 61, hop 48, 80 bins, 251 classes.",
         "  public static let shipped = ZipformerIO(",
         f'    windowFrames: {io["T"]},', f'    hopFrames: {io["hop"]},', f'    featureDim: {io["featureDim"]},',
         f'    vocabSize: {io["vocabSize"]},', "    inputs: ["]
lines += [f'      .init(name: "{i["name"]}", dims: {i["dims"]}, dtype: .{"int64" if i["dtype"] == "int64" else "float32"}),'
          for i in io["inputs"]]
lines += ["    ]", "  )", "}"]
(SRC / "ZipformerIO.generated.swift").write_text("\n".join(lines) + "\n")
